controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\SqlDataProvider;
use yii\data\ActiveDataProvider;
//use app\models\Cascos;
//use app\models\Corazas;
//use app\models\Jugadores;
//use app\models\Materiales;

class SiteController extends Controller
{
     public function actionConsultamaterial(){
        $dataProvider = new SqlDataProvider(['sql'=>'SELECT codigoCA AS CodigoCasco, talla FROM cascos 
                                                        WHERE codigoJU IS NULL
                                                        UNION 
                                                        SELECT "CodigoCoraza", "Talla"
                                                        UNION
                                                        SELECT codigoCO AS CodigoCoraza, talla FROM corazas
                                                        WHERE codigoJU IS NULL'
            
        ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['CodigoCasco', 'talla'],
            "titulo"=>"Material disponible",
            "enunciado"=>"Cascos y corazas en desuso",
        ]);
     }
     
     public function actionConsultamaterialcampo(){
        $dataProvider = new SqlDataProvider(['sql'=>'SELECT codigoMA, tipo FROM materiales WHERE estado = "Bueno"'
            
        ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['codigoMA', 'tipo'],
            "titulo"=>"Material de campo disponible",
            "enunciado"=>"Materiales de campo en buen estado",
        ]);
     }
     
     public function actionConsultaasociar(){
        $dataProvider = new SqlDataProvider(['sql'=>'SELECT DISTINCT jugadores.codigoJU, nombre, apellidos, telefono, codigoCA, codigoCO FROM jugadores
                                                            INNER JOIN cascos ON cascos.codigoJU=jugadores.codigoJU
                                                            INNER JOIN corazas ON corazas.codigoJU=jugadores.codigoJU'
             
        ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['codigoJU', 'nombre', 'apellidos', 'telefono', 'codigoCA', 'codigoCO'],
            "titulo"=>"Cascos y corazas",
            "enunciado"=>"Jugadores con sus cascos y corazas",
        ]);
     }
     
     public function actionConsultaestadoma(){
        $dataProvider = new SqlDataProvider(['sql'=>'SELECT DISTINCT codigoMA, tipo, estado FROM materiales 
                                                     WHERE estado="roto"'
            
        ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['codigoMA', 'tipo', 'estado'],
            "titulo"=>"Material de campo",
            "enunciado"=>"Material en mal estado",
        ]);
     }
     
     public function actionConsultaprecio(){
        $dataProvider = new SqlDataProvider(['sql'=>'SELECT DISTINCT (SELECT DISTINCT SUM(precio) AS TotalCascos FROM cascos) 
             + (SELECT DISTINCT SUM(precio) AS TotalCorazas FROM corazas) 
             + (SELECT DISTINCT SUM(precio) AS TotalMaterial FROM materiales) AS TotalInvertido'
            
        ]);
        $dataProvider2 = new SqlDataProvider(['sql'=>'SELECT DISTINCT SUM(precio) AS TotalCascos FROM cascos'
            
        ]);
        
        $dataProvider3 = new SqlDataProvider(['sql'=>'SELECT DISTINCT SUM(precio) AS TotalCorazas FROM corazas'
            
        ]);
        
        $dataProvider4 = new SqlDataProvider(['sql'=>'SELECT DISTINCT SUM(precio) AS TotalMaterial FROM materiales'
            
        ]);
        
        return $this->render("inversiones",[
            "resultados"=>$dataProvider,
            "campos"=>['TotalInvertido'],
            "titulo"=>"Dinero Invertido",
            "enunciado"=>"Cantidad total invertida",
            "resultados2"=>$dataProvider2,
            "resultados3"=>$dataProvider3,
            "resultados4"=>$dataProvider4
        ]);
     }
     
     public function actionConsultaprecio2(){
        $dataProvider = new SqlDataProvider(['sql'=>'SELECT DISTINCT SUM(precio) AS TotalCascos FROM cascos'
            
        ]);
        return $this->render("inversiones",[
            "resultados2"=>$dataProvider,
            "campos"=>['TotalCascos'],
            "titulo"=>"Dinero Invertido",
            "enunciado"=>"Cantidad total invertida",
        ]);
     }
     
     public function actionPosicion1(){
         $dataProvider = new SqlDataProvider(['sql'=>'SELECT COUNT(posicion) cantidad, posicion FROM jugadores GROUP BY posicion']);
       
         
         return $this->render("posiciones",[
             "dataProvider"=>$dataProvider,
         ]);
     }
     
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    
    
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <P>
            
        </P>
        <h1 class="display-4">GESTIÓN DE MATERIAL</h1>
    </div>

    <div class="body-content">

        <div class="row margeniz" >
            <div class="col-2 card">
                <p>
               
               </p>
               MATERIAL LIBRE  
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
                   <?= Html::a('Acceder',['site/consultamaterial'],['class' =>'btn btn-primary'])?>
               </p>
            </div>
            <div class="col-2 card" > 
                <p>
               
               </p>
               JUGADORES-MATERIAL
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
                   <?= Html::a('Acceder',['site/consultaasociar'],['class' =>'btn btn-primary'])?>
               </p>
            </div>     
            <div class="col-6 card">
                <p>
               
               </p>
               MATERIAL A REEMPLAZAR
<p>
               
               </p>
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
                   <?= Html::a('Acceder',['site/consultaestadoma'],['class' =>'btn btn-primary'])?>
               </p>               
            </div>
            <div class="col-2 card">
                <p>
               
               </p>
               INVERSIÓN
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
                   <?= Html::a('Acceder',['site/consultaprecio'],['class' =>'btn btn-primary'])?>
               </p>
            </div>
            <div class="col-2 card  align-center">
                <p>
               
               </p>
               JUGADORES POR POSICIÓN    
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
                   <?= Html::a('Acceder',['site/posicion1'],['class' =>'btn btn-primary'])?>
               </p>
            </div>
            <div class="col-6 card  align-center">
                <p>
               
               </p>
               MATERIAL DE CAMPO     
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
               
               </p>
               <p>
                   <?= Html::a('Acceder',['site/consultamaterialcampo'],['class' =>'btn btn-primary'])?>
               </p>
            </div>
        </div>

    </div>
</div>

views/site/inversiones.php
<?php

use yii\widgets\ListView;
use yii\helpers\Html;
?>
<div class="site-index ">
    
    <div class="body-content ">
       
        <div class="pt-5"> </div>
         <div ><h3 class="titulos">INVERSIÓN DEL CLUB</h3></div>
        <div class="row margenizquierda">
            <br>
            <?=
        ListView::widget([
            'dataProvider' => $resultados4,
            'layout' => "{items}",
            'itemView' => function($model) {
                ?>
                <div class="col-sm-6">
                <div class="cardpos"> 
                    <h3>Total en Material</h3>
                    
                    <?=
                    $model['TotalMaterial'];
                    ?>
                </div>
                </div>
            <?php }]); ?>
          <?=
        ListView::widget([
            'dataProvider' => $resultados3,
            'layout' => "{items}",
            'itemView' => function($model) {
                ?>
                <div class="col-sm-6">  
                <div class="cardpos"> 
                    <h3>Total en Corazas</h3>
                    <?=
                    $model['TotalCorazas'];
                    ?>
                </div>
                </div>
            <?php }]); ?>
            
            <?=
        ListView::widget([
            'dataProvider' => $resultados2,
            'layout' => "{items}",
            'itemView' => function($model) {
                ?>
                <div class="col-sm-6">
                <div class="cardpos"> 
                    <h3>Total en Cascos</h3>
                    <?=
                    $model['TotalCascos'];
                    ?>
                </div>
                </div>
            <?php }]); ?>
             <?=
        ListView::widget([
            'dataProvider' => $resultados,
            'layout' => "{items}",
            'itemView' => function($model) {
                ?>
                <div class="col-sm-6">  
                <div class="cardpos"> 
                    <h3>Total Invertido</h3>
                    <?=
                    $model['TotalInvertido'];
                    ?>
                </div>
                </div>
            <?php }]); ?>
    </div>
</div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/posiciones.php
<?php

use yii\widgets\ListView;
use yii\helpers\Html;
?>
<div class="site-index ">
    
    <div class="body-content ">
       
        <div class="pt-5"> </div>
         <div ><h3 class="titulos">CANTIDAD DE JUGADORES POR POSICIÓN</h3></div>
        <div class="row">
        
          

        <?=
        ListView::widget([
            'dataProvider' => $dataProvider,
            'layout' => "{items}",
            'itemView' => function($model) {
                ?>
                <div class="col-sm-4">  
                <div class="cardpos"> 
                    <br>
                    <?=
                    $model['cantidad'];
                    ?>
                    <?=
                    $model['posicion'];
                    ?>
                </div>
                </div>
            <?php }]); ?>

        <!--             ListView::widget(['dataProvider' => $dataProvider,
                        'itemView' => '_vistaPosiciones', 
                        'summary' => false,
                        'options' => ['tag' => 'div'], 
                        'layout' => "{summary}\n{pager}\n{items}", 
                        ]); -->
    </div>
</div>
</div>

views/site/resultado.php
<?php
use yii\grid\GridView;
?>

<div class="jumbtron">
    <p>
        
    </p>
    <h2><?=$titulo?></h2>
    <p class="lead"><?= $enunciado ?></p>
    <div class="well">
    </div>
</div>

<?= GridView::widget([
    'dataProvider'=> $resultados,
    'columns'=> $campos
        
]); ?>